### ISSUE TITLE
Problem finding libpython on Ubuntu

### ISSUE THREAD

**Issue by andreasnoack** [JuliaPy/PyCall.jl#565]
This has caused some problems for CIBot lately
```julia
julia> ENV["PYTHON"]="/usr/bin/python3"
"/usr/bin/python3"

(v1.0) pkg> build PyCall
  Building Conda ─→ `~/.julia/packages/Conda/m7vem/deps/build.log`
  Building PyCall → `~/.julia/packages/PyCall/rUul9/deps/build.log`
┌ Error: Error building `PyCall`:
│ ERROR: LoadError: Couldn't find libpython; check your PYTHON environment variable.
│
│ The python executable we tried was /usr/bin/python3 (= version3.6);
│ the library names we tried were ["libpython3.6m.so", "libpython3.6m", "libpython3.6", "libpython"]
│ and the library paths we tried were AbstractString["/usr/lib","/usr/lib", "/usr", "/usr/lib"]
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] find_libpython(::String) at /home/andreasnoack/.julia/packages/PyCall/rUul9/deps/build.jl:129
│  [3] top-level scope at logging.jl:313
│  [4] top-level scope at /home/andreasnoack/.julia/packages/PyCall/rUul9/deps/build.jl:196
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1038
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:388
│  [9] top-level scope at none:0
│ in expression starting at /home/andreasnoack/.julia/packages/PyCall/rUul9/deps/build.jl:170
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```

**Comment by andreasnoack** [comment]
This one seems able to find `libpython`
```
andreasnoack@anubis:~$ /usr/bin/python3 find_libpython.py --list-all
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
```

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

**Comment by tkf** [comment]
Thanks, good to know.

**Comment by rishisubramanian** [comment]
Just letting you know that I have the same issue on Ubuntu 18.10 (Development). My libpython location is the same at /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0.
`No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Cosmic Cuttlefish (development branch)
Release:        18.10
Codename:       cosmic`

**Comment by tkf** [comment]
If you feel brave you can try #556 with `] add PyCall#remotes/cache/pull/556/head` :)

**Comment by huckl3b3rry87** [comment]
So, the master is fixed?

I am still getting a build error using the latest tagged version
```
================================================================================
INFO: Building PyCall
===============================[ ERROR: PyCall ]================================

LoadError: Couldn't find libpython; check your PYTHON environment variable.

The python executable we tried was python3 (= version 3.5);
the library names we tried were String["libpython3.5m.so", "libpython3.5m", "libpython3.5", "libpython"]
and the library paths we tried were String["/usr/lib", "/usr/lib", "/usr", "/usr/lib"]
while loading /home/mavs/.julia/v0.6/PyCall/deps/build.jl, in expression starting on line 265
```

**Comment by tkf** [comment]
No master still has the problem. #556 is not merged yet.

**Comment by stevengj** [comment]
Fixed by #556

**Comment by andreasnoack** [comment]
Thanks for fixing this. Would it be possible to make a new release? This issue is still causing all `PyCall` dependent packages to fail CIBot testing.
